/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package porj2;

public class App {
    public String getGreeting() {
        return "Hello World! This is my first Gradle Proj";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
